In [1]:
import numpy as np 

In [8]:
myarr = np.array([[3, 6, 32, 7]], np.int64) # double square brackets signify 2D array

In [9]:
myarr[0, 1] # 0th row and 1st column

6

In [11]:
myarr.shape # m rows and n columns

(1, 4)

In [12]:
myarr.dtype # type of bit used

dtype('int64')

# Array creation: Conversion from other python structures

In [13]:
listArray = np.array([[1, 2, 3], [5, 8, 5], [0, 3, 1]])

In [14]:
listArray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [15]:
listArray.dtype

dtype('int32')

In [16]:
listArray.shape

(3, 3)

In [17]:
listArray.size

9

In [18]:
np.array((43, 32, 32, 23, 23))

array([43, 32, 32, 23, 23])

In [19]:
np.array({32, 23, 23, 43, 43, 32}) # object is not efficient that's why int or float should be used

array({32, 43, 23}, dtype=object)

# Array creation: Intrinsic numpy array creation objects

In [20]:
zeros = np.zeros((2, 5)) # will give an array of 2 rows and 5 columns with zeros with dtype float 

In [22]:
zeros 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
rng = np.arange(15) # similar like 'range' means it will give array from 0 to n-1

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
lspace = np.linspace(1, 4, 4) # will give array with 4 elements b/w range 1 to 4 with equal space

In [30]:
lspace

array([1., 2., 3., 4.])

In [31]:
ones = np.ones((2, 5))

In [32]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
emp = np.empty((4, 5)) # array with 4 rows and 5 cols with random elements

In [37]:
emp

array([[7.55074610e-312, 5.73116149e-322, 0.00000000e+000,
        0.00000000e+000, 2.22526399e-307],
       [3.16251369e+180, 1.05776693e-153, 6.03461190e+151,
        1.03586242e-095, 1.67772392e+243],
       [1.16466606e-028, 4.90900643e+252, 1.94918511e-153,
        1.16568549e+253, 7.49511203e+247],
       [1.12284826e+219, 1.94919754e-153, 8.76730942e+252,
        2.59903831e-144, 6.23061928e-307]])

In [38]:
empLike = np.empty_like(lspace) # copy size of existed array and create a random array

In [39]:
empLike

array([1., 2., 3., 4.])

In [40]:
ide = np.identity(45) # 45*45 identity matrix

In [41]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [42]:
arr = np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr = arr.reshape(3, 33) # will reshape array with 3 rows and 33 columns (IMPORTANT)

In [47]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [49]:
arr = arr.ravel() # change arr back to normal

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [1]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [5]:
ar = np.array(x)

In [6]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [7]:
ar.sum(axis=0)

array([12,  8,  9])

In [8]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [9]:
ar.T # transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [10]:
ar.flat # iterator so that we can iterate using loop

In [11]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [12]:
ar.ndim # for number of dimensions

2

In [13]:
ar.nbytes # total bytes consumed by elements of array

36

In [14]:
oneD = np.array([1, 23, 44, 23, 78])

In [15]:
oneD.argmax() # index which contains maximum element

4

In [16]:
oneD.argmin() # index which contains minimum element

0

In [17]:
oneD.argsort() # will give index if the array was sorted

array([0, 1, 3, 2, 4], dtype=int64)

In [18]:
ar.argmin() # will first convert 2d into 1d array and than give the index which contains min element

8

In [19]:
ar. argmax() # will first convert 2d into 1d array and than give the index which contains max element

6

In [20]:
ar.argmax(axis=0) # will do the same task but this tym only on a specific axis

array([2, 1, 1], dtype=int64)

In [21]:
ar.argmax(axis=1) # will do the same task but this tym only on a specific axis

array([2, 2, 0], dtype=int64)

In [22]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [23]:
ar2 = np.array([[1, 2, 1], [2, 4, 1], [5, 7, 2]])

In [24]:
ar + ar2

array([[ 2,  4,  4],
       [ 6,  9,  7],
       [12,  8,  2]])

In [28]:
np.sqrt(ar2) # square root of each element in ar2

array([[1.        , 1.41421356, 1.        ],
       [1.41421356, 2.        , 1.        ],
       [2.23606798, 2.64575131, 1.41421356]])

In [29]:
ar2.sum()

25

In [30]:
ar2.max()

7

In [31]:
ar2.min()

1

In [32]:
np.where(ar>5) # index where elements are greater than 5

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [33]:
np.count_nonzero(ar2) # count nonzero

9

In [34]:
np.nonzero(ar2) # tuple with index of nonzero elements

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [35]:
import sys

In [36]:
py_ar = [0, 4, 55, 2]

In [37]:
np_ar = np.array(py_ar)

In [39]:
sys.getsizeof(1) * len(py_ar)

112

In [41]:
np_ar.itemsize * np_ar.size

16

In [42]:
np_ar.tolist() # numpy array to python list

[0, 4, 55, 2]

# PROBLEM 1 FROM FREECODECAMP 58 MINS VIDEO

In [3]:
prob1freeCode = np.ones((5, 5))

In [4]:
prob1freeCode

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
solFreeCode = np.zeros((3, 3))

In [6]:
solFreeCode

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
solFreeCode[1, 1] = 9

In [8]:
solFreeCode

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [11]:
prob1freeCode[1:-1, 1:-1] = solFreeCode

In [12]:
prob1freeCode

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# BE CAREFUL WHEN COPYING ARRAYS

a = np.array([1, 2, 3])
b = a # THIS DOES NOT MEAN, "array a is assigned to b". It means "array will do the same thing which array does."
b[0] = 100 # THIS WILL ALSO CHANGE IN a
TO AVOID THIS WE HAVE TO USE ".copy()" 

In [17]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b) 

[1 2 3]
[100   2   3]


# BASIC MATHEMATICS 

In [7]:
mathArr1 = np.array([1, 2, 3, 4])
mathArr1 + 2 # same for "-1", "*2", etc

array([3, 4, 5, 6])

In [8]:
mathArr1 ** 2

array([ 1,  4,  9, 16])

In [9]:
np.sin(mathArr1) # trigonometry can also be done using numpy

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**LINEAR ALGEBRA**

In [3]:
linAlg1 = np.ones((2, 3))
linAlg2 = np.full((3, 2), 2)

In [4]:
np.matmul(linAlg1, linAlg2) # IN BUILT MATRIX MULTIPLICATION

array([[6., 6.],
       [6., 6.]])

In [5]:
linAlg3 = np.identity(3)
np.linalg.det(linAlg3)

1.0

**STATISTICS**

min, max, sum, etc..

# REORGANIZING ARRAYS

In [6]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

# LOAD DATA FROM A FILE

In [11]:
fileData = np.genfromtxt('data.txt', delimiter=',')

In [12]:
fileData = fileData.astype('int32')
fileData

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 23,  34,  35,  36,  37,  38,  39],
       [434,  22, 122,   2,  43,   4,   5]])

# BOOLEAN MASKING AND ADVANCE INDEXING

You can index with a list in NumPy 

In [13]:
fileData > 50

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True, False,  True, False, False, False, False]])

In [14]:
fileData[fileData > 50]

array([434, 122])

In [15]:
np.any(fileData > 50, axis=0)

array([ True, False,  True, False, False, False, False])

In [16]:
np.all(fileData > 50, axis=0) # will only return true if all the values in the col are greater than 50

array([False, False, False, False, False, False, False])

In [17]:
(~((fileData > 50) & (fileData < 100)))

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])